---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: bitwarden.secrets
    version: 1.0.1
  - name: community.docker
    version: 4.6.0
  - name: community.general
    version: 10.7.0
  - name: community.sops
    version: 2.0.5
  - name: kubernetes.core
    version: 6.0.0
